<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{a1e7293a-1635-4c1b-8f12-114f4e7f9a94}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// PRUEBA PARA EL MAIN EN LUGAR DEL MASTER//

//no jala //
// primer cosa ///]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>